$background = rgb(0F0202)
$backgroundAlpha = 0F0202

$backgroundAlt = rgb(0F0202)
$backgroundAltAlpha = 0F0202

$foreground = rgb(d99ca0)
$foregroundAlpha = d99ca0

$selected = rgb(CE0C16)
$selectedAlpha = CE0C16

$active = rgb(D01826)
$activeAlpha = D01826

$urgent = rgb(AF0A13)
$urgentAlpha = AF0A13
